Fix type of environmental variables
toradex/torizon-samples pull request #23
Opened 2024-05-24 19:14 UTC by lucasbernardestoradex

The environmental variable was been recognized by different types

2024-05-27 13:03 UTC, brunoaamello requested changes
Hello @lucasbernardestoradex,

Thanks for these corrections.

My comments are just related to wording.

Please also amend the current commit so it refers to the environment variables as "environment variables" and not "environmental variables"

2024-05-27 13:03 UTC, brunoaamello commented on tflite/tflite-rtsp/demos/object-detection/object-detection.py
> +## The system return the variable as String, so it's necessary
```suggestion
## The system returns the variables as Strings, so it's necessary to convert them where we need the numeric value
```

2024-05-27 14:03 UTC, lucasbernardestoradex commented
Hello @leonheldattoradex, could you review and approve these merge request. I'm not allowed to do that.

2024-06-06 20:05 UTC, brunoaamello approved these changes
Thanks @lucasbernardestoradex.

This MR looks good to me.

2024-06-12 21:01 UTC, lucasbernardestoradex commented
@leonheldattoradex Can you please merge this?

2024-06-13 16:44 UTC, leonheldattoradex reviewed
Please change `environmental` to `environment`.

2024-06-13 16:44 UTC, leonheldattoradex commented on tflite/tflite-rtsp/demos/object-detection/object-detection.py
> +USE_HW_ACCELERATED_INFERENCE =True
Space before `True`

2024-06-13 16:44 UTC, leonheldattoradex commented on tflite/tflite-rtsp/demos/object-detection/object-detection.py
> +else:
This cam be simplified to `MINIMUM_SCORE = float(os.environ.get("MINIMUM_SCORE", default=0.55))`.

2024-06-13 16:44 UTC, leonheldattoradex commented on tflite/tflite-rtsp/demos/object-detection/object-detection.py
> +else:
Same in line 41.

2024-06-13 17:13 UTC, lucasbernardestoradex commented
@leonheldattoradex I fixed the name "environmental" and the definition of the environment variables.

2024-06-13 17:21 UTC, leonheldattoradex commented
@lucasbernardestoradex this is the best commit I've ever got from an intern. Not only you applied my suggestion, you did for *every* other case where it applied. Today is a truly glorious day.

2024-06-13 17:21 UTC, merged